# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build application
        run: |
          npm i
          npm run build -- --output-path=./infrastructure/dist
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: infrastructure
          path: infrastructure/*
  build-infra:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Download result
        uses: actions/download-artifact@v2
        with:
          name: infrastructure
      - name: Prepare credentials
        run: |
          mkdir ~/.aws
          echo ${{ secrets.AWS_CRED }} > ~/.aws/credentials
      - name: Build infrastructure
        env:
          CDK_ACCOUNT: ${{ secrets.CDK_ACCOUNT }}
          CDK_REGION: ${{ secrets.CDK_region }}
        run: |
          npm i
          npx cdk deploy --require-approval never
  
