# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          npm i
          ng build
